---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter 
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.7.0
    init: confluentinc/confluent-init-container:2.9.0
  dataVolumeCapacity: 10Gi
  configOverrides:
    server:
      - confluent.metrics.topic.max.message.bytes=8388608  
      - confluent.controlcenter.mode.enable=management
  dependencies:
    kafka:
      bootstrapEndpoint: pkc-xxxxx.us-east-1.aws.confluent.cloud:9092
      authentication:
        type: plain
        jaasConfig:
          secretRef: cluster-demo-credentials
      tls:
        enabled: true
        ignoreTrustStoreConfig: true
    schemaRegistry:
      url: https://psrc-xxxx.us-east-1.aws.confluent.cloud
      authentication:
        type: basic
        basic:
          secretRef: ccloud-sr-credentials
    connect:
      - name: connect-demo
        url: http://connect-demo.confluent.svc.cluster.local:8083
